default_install_hook_types:
  - pre-commit

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry --directory . run black --quiet
        language: system
        files: ^.*\.py$
        fail_fast: true

      - id: mypy
        name: mypy
        entry: poetry --directory . run mypy --config-file pyproject.toml
        language: system
        files: ^.*\.py$
        fail_fast: true

      - id: ruff
        name: ruff
        entry: poetry --directory . run ruff --fix
        language: system
        files: ^.*\.py$
        fail_fast: true
